### PR TITLE
add coal_mining notebook

### PR DESCRIPTION
**Pull request by vindex10**
work in progress.

TODO:

* add more text / descriptions
* separate data into file, read from it
* convert to literate jl.

### CODE REVIEW

**Comment by oschulz** [comment]
Very nice now, with Literate. Should I merge this already, or are you still tweaking things a bit?

**Comment by oschulz** [comment]
We should remove the jupyter notebook though, now that the Literate version is in. And maybe rename "intervals.tsv" to "coal_mining_dataset.tsv" or similar?

**Comment by vindex10** [comment]
it is not yet ready.  i will remove the notebook and i had in mind renaming
the file. I'll do that! still have to write descriptions and make sure docs
are building. it is as mess with paths. it built for me locally but
remotely it says file not found

**Comment by oschulz** [comment]
Great, thanks!

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
